[package]
distribution = "2201.2.1"
org= "ballerinax"
name= "microsoft.onenote"
version= "2.3.0"
authors = ["Ballerina"]
keywords = ["Content & Files/Notes", "Cost/Freemium", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.onenote"
license = ["Apache-2.0"]

[build-options]
observability-included=true
